[org.colinux.devel @ 9524f3101c435934a4abe7fc49fd20d99fc90242] Build scripts and other changes: (by Henry Nestler)  - Patch FLTK-win32 to compile without X11-devel (arg --without-x).  - Separate directory for DOWNLOAD and BUILD.  - MD5 files moved into BUILD directory.  - Separate directory for module output (old _install).  - Clean up build dir after installing cross tools and libs.  - Check installed version of gcc and binutils, not md5sum for cross gcc.  - Check more errorlevels after unzip, bunzip2 and patch.    "error_exit 10", if errors not redirect to logfile, such on unzip or patch.  - Linux as host only for kernel 2.6, fixup for extraversion (configure).  - Update doc/building, installer and package, mark Variables of directories.  - Comment more "installer", instand of "install"  - Python have only two digits in version, check version "2.3+" and    "2.3.4"  --> hack version detection for all "x.y" versions.  - New: "make installer" in ./configure (use wine & Co.)  - New: "make package" in Makefile created from ./configure.    Save symbols in Map files before strip.  - Create ZIP files for daemons and vmlinux (known from autobuild).  - Bug: Don't extract kernel, if ...untar=no and kernel not have    cooperative.h  - Backup Kernel tree, before lose user changes in step untar and patch.
git-svn-id: svn://svn.code.sf.net/p/colinux/code/branches/devel@427 688f6386-cf32-0410-9ead-a596f0484e40

diff --git a/patch/fltk-1.1.4-win32.diff b/patch/fltk-1.1.4-win32.diff
--- a/patch/fltk-1.1.4-win32.diff
+++ b/patch/fltk-1.1.4-win32.diff
@@ -8,3 +8,15 @@
  #endif // !__GNUC__ || __GNUC__ >= 3
  
  
+diff -urN fltk-1.1.4/configure fltk-1.1.4-patch-noX/configure
+--- fltk-1.1.4-patch-noX/configure
++++ fltk-1.1.4/configure
+@@ -8040,7 +8040,7 @@
+ fi
+ 
+ 
+-	if test x$no_x = xyes; then
++	if test x$no_x = xyes -a x$have_x != xdisabled; then
+ 	    { { echo "$as_me:$LINENO: error: Configure could not find required X11 libraries" >&5
+ echo "$as_me: error: Configure could not find required X11 libraries" >&2;}
+    { (exit aborting.); exit aborting.; }; }
